apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-component-groups
spec:
  storages:
    meta:
      memory: true
    object:
      memory: true
  global:
    image: ghcr.io/risingwavelabs/risingwave:v0.1.16
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
  components:
    meta:
      groups:
      - name: default
        replicas: 1
    frontend:
      groups:
      - name: default
        replicas: 1
    compute:
      groups:
      - name: default
        replicas: 1
    compactor:
      groups:
      - name: default
        replicas: 1